# Example for: model.assess_normalized_dope()

from modeller import *
from modeller.scripts import complete_pdb

env = environ()
env.libs.topology.read(file='$(LIB)/top_heav.lib')
env.libs.parameters.read(file='$(LIB)/par.lib')

# Read a model previously generated by Modeller's automodel class
mdl = complete_pdb(env, 'C:\Users\ivbie\Documents\2020 - Projetos mestrado\CYFIP2\database\CYFIP2_WT\UKNP.B99990001')

zscore = mdl.assess_normalized_dope()
